== Optional Schema Constraints for Neo4j

This is alpha-state, please use with care on toy-stores only. No guarantees whatsoever.


=== Build & Install

[source,shell]
----
git clone https://github.com/jexp/neo4j-constraints.git
cd neo4j-constraints
mvn install
cp target/constraints-2.1-SNAPSHOT.jar /path/to/neo4j-community-2.1.5/plugins
/path/to/neo4j-community-2.1.5/bin/neo4j restart
----

=== Usage

There is a new shell command called `constrain`

Currently you can only _add_ cardinality constraints.

Here are some examples:

----
CONSTRAIN (:Person)-[:WORKS_FOR]-> (:Company) TO many : 1
CONSTRAIN (:Person)-[:REPORTS_TO]->(:Manager) TO 1..3 : 0..1
CONSTRAIN (:Person)-[MARRIED_TO]-  (:Person)  TO one : one
----

=== How does it work?

Using a Neo4j Shell command for adding cardinality constraints and a transaction-event-handler to enforce them.
The constraints are stored in a graph-property and so propagated across a cluster.

The TX-Handler only looks at nodes with the relevant labels and checks the degree for those relationship-types,
direction and optionally end-node-labels.
It throws an exception if the degree min or max for one of the two sides is violated.

=== Next Steps

* property-type constraints
* property value constraints (formats, min, max, min-length, max-length, defaults?)
* ???
